"use client";
import Navbar from "@/components/Navbar";
import client from "@/services/client";
import "@/styles/globals.css";
import { ApolloProvider } from "@apollo/client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-background`}>
        <Navbar />
        <ApolloProvider client={client}>{children}</ApolloProvider>
      </body>
    </html>
  );
}
